name: ci

on: [push]

jobs:
  build:
    name: ci
    runs-on: macOS-latest
    strategy:
      matrix:
        env:
          - sdk: iphonesimulator13.0
            destination: platform=iOS Simulator,name=iPhone 11,OS=13.0
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v1
    - name: Install Carthage
      continue-on-error: true
      run: | 
        brew install carthage
        carthage bootstrap --platform iOS
    - name: Test Automation
      run: |
        set -o pipefail && xcodebuild clean build test \
          -project "$PROJECT" \
          -scheme "$SCHEME" \
          -sdk "$SDK" \
          -destination "$DESTINATION" \
          -configuration Debug \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c;
      env:
        PROJECT: CleanRoute.xcodeproj
        SCHEME: CleanRoute
        SDK: ${{ matrix.env.sdk }}
        DESTINATION: ${{ matrix.env.destination }}
        DEVELOPER_DIR: /Applications/Xcode_11.app/Contents/Developer
